name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/vector.png
    - assets/page-1/images/vector-VZi.png
    - assets/page-1/images/ichumidity.png
    - assets/page-1/images/icprofile.png
    - assets/page-1/images/group-9.png
    - assets/page-1/images/icwarningpassword.png
    - assets/page-1/images/icemail.png
    - assets/page-1/images/ictime.png
    - assets/page-1/images/vector-BPn.png
    - assets/page-1/images/icemail-BRr.png
    - assets/page-1/images/ictime-QAC.png
    - assets/page-1/images/icloginlogo.png
    - assets/page-1/images/ictime-42C.png
    - assets/page-1/images/ictime-sui.png
    - assets/page-1/images/icperson.png
    - assets/page-1/images/icpassword.png
    - assets/page-1/images/icsignuplogo.png
    - assets/page-1/images/icperson-SRW.png
    - assets/page-1/images/ichappy.png
    - assets/page-1/images/icperson-pqW.png
    - assets/page-1/images/teenyicons-plant-solid.png
    - assets/page-1/images/ichappy-4Yg.png
    - assets/page-1/images/ichome.png
    - assets/page-1/images/vector-jNQ.png
    - assets/page-1/images/icperson-6qn.png
    - assets/page-1/images/vector-Eyv.png
    - assets/page-1/images/vector-mmS.png
    - assets/page-1/images/ichappy-mCL.png
    - assets/page-1/images/ichappy-H28.png
    - assets/page-1/images/ictime-rPr.png
    - assets/page-1/images/vector-Zi8.png
    - assets/page-1/images/iclocation.png
    - assets/page-1/images/ichappy-iNU.png
    - assets/page-1/images/icperson-a96.png
    - assets/page-1/images/icperson-KyA.png
    - assets/page-1/images/icperson-Rhz.png
    - assets/page-1/images/ictime-kxY.png
    - assets/page-1/images/ictime-u3E.png
    - assets/page-1/images/ictime-QKa.png
    - assets/page-1/images/icrain.png
    - assets/page-1/images/ichappy-qZa.png
    - assets/page-1/images/ictime-HQt.png
    - assets/page-1/images/icsearch.png
    - assets/page-1/images/ichappy-byr.png
    - assets/page-1/images/iclogout.png
    - assets/page-1/images/icperson-gnt.png
    - assets/page-1/images/vector-Xyr.png
    - assets/page-1/images/icfalse.png
    - assets/page-1/images/vector-dYU.png
    - assets/page-1/images/icfalse-bb6.png
    - assets/page-1/images/vector-MEp.png
    - assets/page-1/images/vector-p5n.png
    - assets/page-1/images/itemimage-bg.png
    - assets/page-1/images/ictime-yWp.png
    - assets/page-1/images/vector-Pix.png
    - assets/page-1/images/ichappy-qYt.png
    - assets/page-1/images/icperson-9CU.png
    - assets/page-1/images/icperson-Nd6.png
    - assets/page-1/images/ichome-kvU.png
    - assets/page-1/images/ictime-5qa.png
    - assets/page-1/images/ictemperature.png
    - assets/page-1/images/vector-oMz.png
    - assets/page-1/images/ichappy-8Rv.png
    - assets/page-1/images/rectangle-7.png
    - assets/page-1/images/vector-Y3z.png
    - assets/page-1/images/icsearch-J3A.png
    - assets/page-1/images/itemimage.png
    - assets/page-1/images/vector-8at.png
    - assets/page-1/images/itemimage-Tt4.png
    - assets/page-1/images/rectangle-7-LKJ.png
    - assets/page-1/images/icrain-ydA.png
    - assets/page-1/images/icperson-6Up.png
    - assets/page-1/images/itemimage-bg-f28.png
    - assets/page-1/images/itemimage-pL8.png
    - assets/page-1/images/ictemperature-2DE.png
    - assets/page-1/images/ichappy-HSp.png
    - assets/page-1/images/ichumidity-FgU.png
    - assets/page-1/images/itemimage-7C4.png
    - assets/page-1/images/bi-info-circle-fill.png
    - assets/page-1/images/icdate.png
    - assets/page-1/images/vector-rJ4.png
    - assets/page-1/images/icperson-4gp.png
    - assets/page-1/images/vector-16G.png
    - assets/page-1/images/ictemperature-WSL.png
    - assets/page-1/images/vector-U8G.png
    - assets/page-1/images/vector-yKv.png
    - assets/page-1/images/ictime-Y88.png
    - assets/page-1/images/icemailsubmitlogo.png
    - assets/page-1/images/ichumidity-qHa.png
    - assets/page-1/images/iclocation-B6Y.png
    - assets/page-1/images/icperson-Lt8.png
    - assets/page-1/images/icfalse-tPr.png
    - assets/page-1/images/icperson-eP2.png
    - assets/page-1/images/iclocation-jvG.png
    - assets/page-1/images/icperson-KQc.png
    - assets/page-1/images/icperson-Nhe.png
    - assets/page-1/images/icrain-8B2.png
    - assets/page-1/images/ichumidity-Cwa.png
    - assets/page-1/images/icrain-ZBW.png
    - assets/page-1/images/icrain-6x8.png
    - assets/page-1/images/iclocation-Qxp.png
    - assets/page-1/images/vector-Nek.png
    - assets/page-1/images/vector-k16.png
    - assets/page-1/images/ichumidity-WFA.png
    - assets/page-1/images/iclocation-HQt.png
    - assets/page-1/images/vector-9hz.png
    - assets/page-1/images/ictemperature-1VJ.png
    - assets/page-1/images/ictemperature-MZA.png
    - assets/page-1/images/ichumidity-U7z.png
    - assets/page-1/images/ictemperature-pBr.png
    - assets/page-1/images/itemimage-bg-gWt.png
    - assets/page-1/images/vector-LFr.png
    - assets/page-1/images/icrain-fov.png
    - assets/page-1/images/vector-suz.png
    - assets/page-1/images/ictime-x3a.png
    - assets/page-1/images/icrain-d9i.png
    - assets/page-1/images/ichumidity-cUp.png
    - assets/page-1/images/ictemperature-18t.png
    - assets/page-1/images/ictemperature-AGg.png
    - assets/page-1/images/ichumidity-eoz.png
    - assets/page-1/images/ictemperature-nQQ.png
    - assets/page-1/images/ichumidity-eSc.png
    - assets/page-1/images/iclocation-cPS.png
    - assets/page-1/images/vector-C8Y.png
    - assets/page-1/images/icdate-93n.png
    - assets/page-1/images/vector-hqz.png
    - assets/page-1/images/icrain-sVa.png
    - assets/page-1/images/group-25.png
    - assets/page-1/images/icrain-Ei4.png
    - assets/page-1/images/auto-group-3poe.png
    - assets/page-1/images/itemimage-J1E.png
    - assets/page-1/images/ictime-ByA.png
    - assets/page-1/images/itemimage-bg-4L8.png
    - assets/page-1/images/vector-fXW.png
    - assets/page-1/images/ichappy-1QL.png
    - assets/page-1/images/icsearch-PxU.png
    - assets/page-1/images/icsearch-jmS.png
    - assets/page-1/images/itemimage-bg-PD2.png
    - assets/page-1/images/icrain-i88.png
    - assets/page-1/images/vector-PYL.png
    - assets/page-1/images/icemail-Rzp.png
    - assets/page-1/images/vector-naU.png
    - assets/page-1/images/ictime-9A8.png
    - assets/page-1/images/iclocation-J32.png
    - assets/page-1/images/vector-raL.png
    - assets/page-1/images/icperson-DQt.png
    - assets/page-1/images/itemimage-bg-Nvt.png
    - assets/page-1/images/itemimage-bg-eNc.png
    - assets/page-1/images/vector-XhJ.png
    - assets/page-1/images/itemimage-bx4.png
    - assets/page-1/images/itemimage-bg-9Tn.png
    - assets/page-1/images/ichumidity-tZe.png
    - assets/page-1/images/itemimage-bg-a72.png
    - assets/page-1/images/itemimage-bg-iyv.png
    - assets/page-1/images/itemimage-nZn.png
    - assets/page-1/images/ictime-Che.png
    - assets/page-1/images/itemimage-bg-6Bz.png
    - assets/page-1/images/ictemperature-zPS.png
    - assets/page-1/images/vector-gqN.png
    - assets/page-1/images/vector-N9v.png
    - assets/page-1/images/ictemperature-yAQ.png
    - assets/page-1/images/icrain-kf2.png
    - assets/page-1/images/icrain-XrY.png
    - assets/page-1/images/icrain-iiU.png
    - assets/page-1/images/ictemperature-KfN.png
    - assets/page-1/images/ichumidity-4QQ.png
    - assets/page-1/images/iclocation-c8g.png
    - assets/page-1/images/ictemperature-k9e.png
    - assets/page-1/images/ichumidity-qKW.png
    - assets/page-1/images/itemimage-2eC.png
    - assets/page-1/images/icdate-3ix.png
    - assets/page-1/images/vector-me8.png
    - assets/page-1/images/vector-KvY.png
    - assets/page-1/images/itemimage-bg-RgU.png
    - assets/page-1/images/ichumidity-roi.png
    - assets/page-1/images/ichumidity-m5a.png
    - assets/page-1/images/icrain-nwS.png
    - assets/page-1/images/ichumidity-NMv.png
    - assets/page-1/images/iclocation-ckg.png
    - assets/page-1/images/ictemperature-7hS.png
    - assets/page-1/images/itemimage-3rG.png
    - assets/page-1/images/itemimage-9AY.png
    - assets/page-1/images/icrain-SyW.png
    - assets/page-1/images/ictime-N6U.png
    - assets/page-1/images/ichumidity-TiY.png
    - assets/page-1/images/itemimage-bg-sXv.png
    - assets/page-1/images/vector-xBJ.png
    - assets/page-1/images/icrain-pjr.png
    - assets/page-1/images/ictime-ZiQ.png
    - assets/page-1/images/vector-HzG.png
    - assets/page-1/images/ichappy-Jhn.png
    - assets/page-1/images/bi-info-circle-fill-DUc.png
    - assets/page-1/images/vector-43A.png
    - assets/page-1/images/icsearch-UVn.png
    - assets/page-1/images/vector-X44.png
    - assets/page-1/images/icperson-bLL.png
    - assets/page-1/images/ichappy-wYU.png
    - assets/page-1/images/ichappy-utk.png
    - assets/page-1/images/icperson-FX6.png
    - assets/page-1/images/ictime-B9r.png
    - assets/page-1/images/ictime-GeL.png
    - assets/page-1/images/ichappy-EHe.png
    - assets/page-1/images/ictemperature-m7n.png
    - assets/page-1/images/ichappy-5di.png
    - assets/page-1/images/icperson-NEc.png
    - assets/page-1/images/icperson-PCk.png
    - assets/page-1/images/ictemperature-vqW.png
    - assets/page-1/images/icneutral.png
    - assets/page-1/images/icperson-g6L.png
    - assets/page-1/images/vector-SaL.png
    - assets/page-1/images/icsad.png
    - assets/page-1/images/ictime-Hi8.png
    - assets/page-1/images/icneutral-cz4.png
    - assets/page-1/images/icsad-fKE.png
    - assets/page-1/images/icneutral-reL.png
    - assets/page-1/images/ichappy-CkG.png
    - assets/page-1/images/ichappy-Kmz.png
    - assets/page-1/images/icsad-xxp.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
